# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Blood_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(2, 'AB'), (3, '0'), (0, 'A'), (1, 'B')])),
                ('RH', models.BooleanField(choices=[(False, '-'), (True, '+')])),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_acount', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Donor_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone_num', models.CharField(max_length=20)),
                ('card_created_date', models.DateTimeField(auto_now_add=True)),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='donor_card',
            name='card_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Employee'),
        ),
        migrations.AddField(
            model_name='donor_card',
            name='id_address_perm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perm', to='isnts.Address'),
        ),
        migrations.AddField(
            model_name='donor_card',
            name='id_address_temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp', to='isnts.Address'),
        ),
        migrations.AddField(
            model_name='donor_card',
            name='id_blood_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Blood_type'),
        ),
        migrations.AddField(
            model_name='donor',
            name='id_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isnts.Donor_card'),
        ),
        migrations.AddField(
            model_name='donor',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
