# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nts',
            name='secret_key',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
