# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorcard',
            name='date_of_birth',
        ),
    ]
