# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='id_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isnts.DonorCard'),
        ),
    ]
