# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='id_donor',
        ),
        migrations.RemoveField(
            model_name='blood',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='blood',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='blood',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='bloodextraction',
            name='blood_taken',
        ),
        migrations.AddField(
            model_name='bloodextraction',
            name='barcode',
            field=models.CharField(default='12345678', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodextraction',
            name='blood_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isnts.BloodType'),
        ),
        migrations.AddField(
            model_name='bloodextraction',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'new'), (1, 'ready for expedition'), (2, 'shipped')], default=0),
        ),
        migrations.DeleteModel(
            name='Barcode',
        ),
        migrations.DeleteModel(
            name='Blood',
        ),
        migrations.DeleteModel(
            name='Expedition',
        ),
    ]
