# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0002_auto_20170106_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
