# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 13:27
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0002_auto_20161115_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donorcard',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='donorcard',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='donor',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='donorcard',
            name='id',
        ),
        migrations.AddField(
            model_name='donorcard',
            name='donor_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isnts.Donor'),
            preserve_default=False,
        ),
    ]
