# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isnts', '0002_auto_20161103_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('subheader', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location_info', models.CharField(max_length=50, null=True)),
                ('gps_lon', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('gps_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('other_contact', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('id_boss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Office_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('height', models.DecimalField(decimal_places=6, max_digits=6)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'male'), (1, 'female')])),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(4, 'Zilinsky'), (0, 'Bratislavsky'), (2, 'Trnavsky'), (6, 'Presovsky'), (1, 'Nitriansky'), (3, 'BanskoBystricky'), (5, 'Kosicky')])),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blood_type',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'AB'), (1, 'B'), (3, '0'), (0, 'A')]),
        ),
        migrations.AlterField(
            model_name='donor_card',
            name='info',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Address'),
        ),
        migrations.AddField(
            model_name='nts',
            name='id_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Address'),
        ),
        migrations.AddField(
            model_name='nts',
            name='id_office_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Office_hours'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_answer_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Questionnaire'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isnts.Donor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_nts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isnts.NTS'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='id_nts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isnts.NTS'),
        ),
        migrations.AddField(
            model_name='address',
            name='id_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Region'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_nts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isnts.NTS'),
        ),
    ]
