# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0002_auto_20161227_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
