# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0002_auto_20161124_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodextraction',
            name='blood_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='isnts.BloodType'),
            preserve_default=False,
        ),
    ]
