# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0003_auto_20161227_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nts',
            name='secret_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
