# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0004_auto_20161227_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Town'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donorcard',
            name='can_donate_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorcard',
            name='card_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.Employee'),
        ),
        migrations.AlterField(
            model_name='donorcard',
            name='id_address_perm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perm', to='isnts.Address'),
        ),
        migrations.AlterField(
            model_name='donorcard',
            name='id_address_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp', to='isnts.Address'),
        ),
        migrations.AlterField(
            model_name='donorcard',
            name='id_blood_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.BloodType'),
        ),
        migrations.AlterField(
            model_name='donorcard',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donorcard',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='donorcard',
            name='phone_num',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
