# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0005_auto_20161228_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'female'), (0, 'male')], default=0),
        ),
    ]
