# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0007_auto_20161229_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodextraction',
            name='id_nts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isnts.NTS'),
        ),
        migrations.AlterField(
            model_name='bloodextraction',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bloodextraction',
            name='postpone',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
