# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0009_auto_20161229_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorcard',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
