# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0010_donorcard_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='personal_identification_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
