# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0011_donor_personal_identification_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
        migrations.AlterField(
            model_name='donor',
            name='personal_identification_number',
            field=models.DecimalField(decimal_places=0, default=9090, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together=set([('personal_identification_number',)]),
        ),
    ]
