# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0012_auto_20161230_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together=set([]),
        ),
    ]
