# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isnts', '0013_auto_20161230_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together=set([('personal_identification_number',)]),
        ),
    ]
